version: '3.8'

services:
  web:
    build: .
    container_name: django_app
    command: poetry run daphne -b 0.0.0.0 -p 8000 realmate_challenge.asgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0

  redis:
    image: redis:alpine
    container_name: redis_server
    ports:
      - "6379:6379"

volumes:
  redis-data:
